apiVersion: apps/v1
kind: Deployment
metadata:
  name: openaifrontend
  namespace: apim-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openaifrontend
  template:
    metadata:
      labels:
        app: openaifrontend
        
    spec:
      containers:
      - name: openaifrontend
        image: necipulusoyy9120/openailb-frontend:1.0  # Local image
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
            - name: BACKEND_URL
              value: http://openaibackend-svc
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
         
       


---
apiVersion: v1
kind: Service 
metadata:
  name: openaifrontend-svc
  namespace: apim-lb
spec:
  type: LoadBalancer  # Local için ClusterIP + port-forward önerilir
  selector:
    app: openaifrontend
  ports: 
    - name: http
      port: 80
      targetPort: 8080
